//agregar
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';
//obtener
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_ERROR= 'OBTENER_PRODUCTOS_ERROR';
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
//eliminar
export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO  ='PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR  = 'PRODUCTO_ELIMINAR_ERROR';
//editar
export const PRODUCTO_EDITAR = 'PRODUCTO_EDITAR';
export const COMENZAR_EDICION = 'COMENZAR_EDICION';     
export const PRODUCTO_EDITAR_EXITO  ='PRODUCTO_EDITAR_EXITO';
export const PRODUCTO_EDITAR_ERROR  = 'PRODUCTO_EDITAR_ERROR ';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';